<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta content="webkit" name="renderer">
        <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
        <title>学习8在线系统</title>
        <meta name="description" content="学习8网络课堂是面向个人、学校、培训机构及企业用户的友好、高性价比的在线教育建站系统，为使教育机构能够以最低成本开展在线教学活动、大大降低了传统教育培训机构进入在线教育行业的门槛。" />
        <meta name="keywords" content="学习8网络课堂，在线教育，在线教学" />
        <?php include_once 'common.inc'; ?>
    </head>
    <body>